polls/poll/urls.py
from django.urls import path

from . import views
app_name = 'poll'
urlpatterns = [
    path('',views.index, name='index'),
    
    path('<int:question_id>/',views.detail, name='detail'),
    
    path('<int:question_id>/results/',views.results, name='results'),

    path('<int:question_id>/vote/',views.vote, name='vote'),
 

]

polls/polls/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    
    path('poll/',include('poll.urls')),
    path('admin/', admin.site.urls),
]

polls/poll/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text= models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >=timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

# Create your models here.

polls/poll/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse , Http404 , HttpResponseRedirect
from .models import Question , Choice


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    context = { 'latest_question_list' : latest_question_list }
    return render(request, 'poll/index.html',context)
    
   

def detail(request, question_id):
    question = get_object_or_404(Question,pk=question_id)

    return render(request , 'poll/detail.html',{'question': question })

def results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request, 'poll/results.html',{ 'question':question })

def vote(request, question_id):
    question = get_object_or_404(Question , pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError , Choice.DoesNotExist):
        return render(request,'poll/detail.html',{
            'question' : question,
            'error_messege' : "You didn't select a choice"
        })

    else:
        selected_choice.votes += 1
        selected_choice.save() 
    return HttpResponseRedirect(reverse('poll:results',args=(question.id,)))

# Create your views here.

polls/poll/templates/poll/detail.html
<form action ="{% url 'poll:vote' question.id  %}" 
method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}<h1></legend>
        {% if error_messege %}
              <p><strong>{{ error_messege }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
               <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
               <labeL for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
</fieldset>
<input type="submit" value="vote" >
</form>






{% comment %} <h1>{{ question.question_text }}</h2>
<ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul> {% endcomment %}

polls/poll/templates/poll/index.html
{% if latest_question_list %}
      <ul>
        {% for question in latest_question_list %}
              <li><a href=" {% url 'poll:detail'  question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
      </ul>
{% else %}
    <p>NO polls are available.</p>
    
{% endif %}

polls/poll/templates/poll/results.html
<h1>{{ question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
         <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}"> Vote Again?</a>